### ISSUE TITLE
和Loadrunner测试出来的数据不一样

### ISSUE THREAD

**Issue by liuwenru** [gujiangfei1221/websocket_loadtest#1]
我们测试发现，使用你的工具和Loadrunner测试出来的不一样

**Comment by gujiangfei1221** [comment]
我自己测试的数据，对于性能很好的websocketDemo：
- LoadRunner12设置思考时间1秒，TPS为60；而websocket_loadtest的TPS也是60。也就是说如果刻意控制压测频率，两者工具的数据是一样的
- 如果LoadRunner12和websocket_loadtest不做任何限制，满负荷的压测，对于我测试的demo，LoadRunner12的TPS只能最好维持在6k，而websocket_test可以达到1W+
- 考虑LoadRunner12功能更为完善，相对应的也更为笨重，所以可能同样的负载机配置，websocket_loadtest更为轻量级
> TPS计算公式：TPS = 总请求数/测试时间
